version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: tameruser
      POSTGRES_PASSWORD: tamerpasswd
      POSTGRES_DB: tamerdb
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
  tamer:
    image: docker.io/kubernetesbigdataeg/tamer:1.0.0-SNAPSHOT
    restart: always
    environment:
      MOCK: "true"
      MOCK_TIME: 15
      JAVA_ENABLE_DEBUG: "true"
      POSTGRESQL_URL: "db"
      QUARKUS_HTTP_CORS: "true"
      QUARKUS_HTTP_CORS_ORIGINS: "http://localhost, http://localhost:9000"
      QUARKUS_HTTP_CORS_METHODS: "GET,PUT,POST"
      QUARKUS_HTTP_CORS_HEADERS: "accept,authorization,content-type,x-requested-with,x-foobar"
      QUARKUS_HTTP_CORS_EXPOSED_HEADERS: "Content-Disposition"
      QUARKUS_HTTP_CORS_ACCESS_CONTROL_MAX_AGE: "24H"
      QUARKUS_HTTP_CORS_ACCESS_CONTROL_ALLOW_CREDENTIALS: "true"
    ports:
      - 8080:8080
    depends_on:
      - db
